[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.bench]
toolchain = "nightly"
command = "cargo"
args = ["bench", "${@}"]

[tasks.bench-slow]
toolchain = "nightly"
command = "cargo"
args = ["bench", "--no-default-features", "--features", "serde,std", "${@}"]

# Always test no-std with std tests
[tasks.test]
dependencies = ["test-no-std"]
command = "cargo"
args = ["test"]

[tasks.format]
workspace = true
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.outdated]
install_crate = "cargo-outdated"
command = "cargo"
args = ["outdated", "-R"]

[tasks.test-all]
dependencies = [
    "test-no-std",
    "test-default",
    "test-legacy-ops",
    "test-db",
    "test-serde"
]

[tasks.test-db]
dependencies = [
    "test-db-postgres",
    "test-db-tokio-postgres",
    "test-db-diesel-postgres"
]

[tasks.test-serde]
dependencies = [
    "test-serde-float",
    "test-serde-str",
    "test-serde-str-float",
    "test-serde-arbitrary-precision",
    "test-serde-arbitrary-precision-float"
]

[tasks.test-no-std]
command = "cargo"
args = ["test", "--no-default-features"]

[tasks.test-default]
command = "cargo"
args = ["test", "--workspace", "--features=default"]

[tasks.test-legacy-ops]
command = "cargo"
args = ["test", "--workspace", "--features=legacy-ops"]

[tasks.test-db-postgres]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=db-postgres"]

[tasks.test-db-tokio-postgres]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=db-tokio-postgres"]

[tasks.test-db-diesel-postgres]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=db-diesel-postgres"]

[tasks.test-serde-float]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=serde-float"]

[tasks.test-serde-str]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=serde-str"]

[tasks.test-serde-str-float]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=serde-str,serde-float"]

[tasks.test-serde-arbitrary-precision]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=serde-arbitrary-precision"]

[tasks.test-serde-arbitrary-precision-float]
command = "cargo"
args = ["test", "--workspace", "--tests", "--features=serde-arbitrary-precision,serde-float"]
