[package]
name = "rust_decimal_macros"
version = "1.1.0"
authors = ["Paul Mason <paul@form1.co.nz>"]
edition = "2018"

description = "Shorthand macros to assist creating Decimal types."
documentation = "https://docs.rs/rust_decimal/"
repository = "https://github.com/paupino/rust-decimal"
readme = "../README.md"

keywords = ["decimal","financial","fixed","precision"]
categories = ["science","data-structures"]

license = "MIT"

[badges]
travis-ci = { repository = "paupino/rust-decimal", branch = "master" }

[dependencies]
rust_decimal = { path = "..", version = "1.1.0" }
rust_decimal_macro_impls = { path = "../macro_impl", version = "1.1.0" }
proc-macro-hack = "0.5"
