[package]
name = "rust_decimal_macros"
version = "1.10.2"
authors = ["Paul Mason <paul@form1.co.nz>"]
edition = "2018"
description = "Shorthand macros to assist creating Decimal types."
documentation = "https://docs.rs/rust_decimal/"
repository = "https://github.com/paupino/rust-decimal"
readme = "../README.md"
keywords = ["decimal","financial","fixed","precision"]
categories = ["science","data-structures"]
license = "MIT"

[dependencies]
rust_decimal = { path = "..", version = "1.10.2" }
quote = "1.0"

[lib]
proc-macro = true
